// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DBService is an autogenerated mock type for the DBService type
type DBService struct {
	mock.Mock
}

// AddRow provides a mock function with given fields: message
func (_m *DBService) AddRow(message string) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
